# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: Install Node.js
- script: |
    npm install
  displayName: Install Dependencies
- script: |
    output=$(node scripts/retrieveDownloadLink.js win)
    curl "$output" --output $(Agent.TempDirectory)/edge.zip
  displayName: Downloading Edge Zip (Windows x64)
- script: |
    chmod +rwx scripts/pipelineUnzipEdge.sh
    ./scripts/pipelineUnzipEdge.sh $(Agent.TempDirectory)/edge.zip $(Agent.TempDirectory)/edge
  displayName: Extracting DevTools Files
- script: |
    export EDGE_CHROMIUM_PATH=$(Agent.TempDirectory)/edge/src
    export EDGE_CHROMIUM_OUT_DIR=Release
    npm run build
  displayName: Building
- script: |
    export EDGE_CHROMIUM_PATH=$(Agent.TempDirectory)/edge/src
    export EDGE_CHROMIUM_OUT_DIR=Release
    npm run test
  displayName: Linting and Testing
- script: |
    export EDGE_CHROMIUM_PATH=$(Agent.TempDirectory)/edge/src
    export EDGE_CHROMIUM_OUT_DIR=Release
    npm run package
  displayName: Creating .vsix
- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    Contents: '*.vsix'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'